bigheader: "Configuration"
abstract: "Configuration for using and learning about HoneyTrap."
toc:
- docs/config/index.md
- title: Listeners
  path: docs/config/listeners.md
  section:
  - docs/config/listeners/socket.md
  - docs/config/listeners/canary.md
  - docs/config/listeners/raw.md
  - docs/config/listeners/netstack.md
- title: Services
  path: docs/config/services.md
  section:
  - docs/config/services/ssh/authentication.md
  - docs/config/services/ssh/service.md
  - docs/config/services/ssh/proxy.md
  - docs/config/services/vnc/service.md
  - docs/config/services/ipp/service.md
  - docs/config/services/http/service.md
  - docs/config/services/http/proxy.md
  - docs/config/services/dns/service.md
  - docs/config/services/dns/proxy.md
  - docs/config/services/smtp/service.md
  - docs/config/services/telnet/service.md
  - docs/config/services/elasticsearch/service.md
  - docs/config/services/smb/service.md
  - docs/config/services/ntp/service.md
  - docs/config/services/ftp/service.md
  - docs/config/services/redis/service.md
- title: Directors
  path: docs/config/directors.md
  section:
  - docs/config/directors/lxc.md
  - docs/config/directors/remote.md
- title: Channels
  path: docs/config/channels.md
  section:
  - docs/config/channels/filters.md
  - docs/config/channels/splunk.md
  - docs/config/channels/elasticsearch.md
  - docs/config/channels/kafka.md
  - docs/config/channels/raven.md
  - docs/config/channels/console.md
  - docs/config/channels/file.md
- title: Examples
  path: docs/config/examples.md
  section:
  - docs/config/examples/cowrie.md
